# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ca20ff95e55ab885353115efd04cb3341b50164481015130770bb979e901bb6ccad4cd96405efc7fbfb9db2c6688bdcb2d87a8a25e8f29d9f9bafbce14b13f

test:
  secret_key_base: af6405cca8af3c29a08c7789e6fe321db7b545f8e7ee2be97c0db4814552bd1a1054c9d9961aac0229870e80d51670c87f95e5646d8c3c48935e4d7a3ed694fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
